# Generated by Django 6.0.2 on 2026-03-16 00:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled Song', help_text='Display title of the song.', max_length=200)),
                ('bpm', models.IntegerField(default=120, help_text='Beats per minute (30–300).', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(300)])),
                ('decay_factor', models.FloatField(default=0.996, help_text='KS decay multiplier (0.9–0.999). Closer to 1 = slower decay.', validators=[django.core.validators.MinValueValidator(0.9), django.core.validators.MaxValueValidator(0.999)])),
                ('data', models.JSONField(default=dict, help_text='Song data including notes array.')),
                ('is_preset', models.BooleanField(default=False, help_text='Whether this song is a built-in preset.')),
                ('description_en', models.TextField(blank=True, default='')),
                ('description_es', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='Owner of the song. Null for presets.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'song',
                'verbose_name_plural': 'songs',
                'ordering': ['-created_at'],
            },
        ),
    ]
